repos:
  - repo: local
    hooks:
      - id: ktlint
        name: ktlint
        entry: scripts/ktlint.sh
        language: system
        files: \.kt$
#        args:
#          - --color
#          - --color-name=Red
#          - --editorconfig
#          - ./.editorconfig
